[project]
name = "effect_sdk"
version = "0.0.1"
authors = [
        { name="Effect Core Team", email="hello@effect.ai"}
]
description = "Effect Network SDK"
readme = "README.md"


[build-system]
requires = ["setuptools>=61.0", "pyntelope"]
build-backend = "setuptools.build_meta"